<p><img alt="udeA logo" height="150px" src="https://github.com/freddyduitama/images/blob/master/logo.png?raw=true" align="left" hspace="50px" vspace="0px" style="width:107px;height:152px;"></p>
<h1><font color='0B5345'> <center>
Numpy </center></font></h1>
<h2><font color='0B5345'> <center>
General Review</center></font></h2>
<font  face="Courier New" size="3">
<p1><center> Juliana Moreno Rada</center></p1>



<p3><center><b><font color='0B5345' face="Lucida Calligraphy,Comic Sans MS,Lucida Console" size="5">Universidad de Antioquia</font></b> </center></p3>

NumPy (Numerical Python) provides an efficient interface to store and operate on dense data buffers. ​In some ways, NumPy arrays are like Python’s built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size.

In [4]:
#import numpy​
import numpy as np

We can use np.array to create arrays (ndarrays) from Python lists. NumPy is constrained to arrays that all contain the same type. ​(If types do not match, NumPy will upcast if possible).

In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

For larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy​.

In [3]:
np.zeros(10, dtype='int') # Array with ten entries in zero​


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((2, 5), dtype = 'float') #Array, two rows, five columns, all entries with the value one​


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((2, 5), 3.1416) #two rows, five columns, all entries with the value of 3.1416​

array([[3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
       [3.1416, 3.1416, 3.1416, 3.1416, 3.1416]])

**Atributes**

In [8]:
array_example = np.random.randint(10, size=(3, 4, 5))
print("Number of dimensions: ", array_example.ndim)
print("Shape: ", array_example.shape)
print("Size: ", array_example.size)
print("Type: ", array_example.dtype)
print("Number of dimensions: ", array_example.itemsize)
print("Number of dimensions: ", array_example.nbytes)

Number of dimensions:  3
Shape:  (3, 4, 5)
Size:  60
Type:  int64
Number of dimensions:  8
Number of dimensions:  480


In [9]:
array_example

array([[[0, 2, 4, 2, 6],
        [4, 4, 0, 1, 8],
        [3, 8, 4, 8, 3],
        [2, 1, 1, 3, 8]],

       [[9, 0, 6, 2, 5],
        [6, 1, 0, 2, 6],
        [0, 9, 4, 5, 2],
        [9, 7, 5, 2, 9]],

       [[5, 2, 9, 2, 6],
        [1, 5, 4, 8, 9],
        [6, 0, 9, 3, 4],
        [8, 5, 6, 3, 2]]])

**Slicing**

In [13]:
array_example = np.random.randint(10, size=(3, 4, 5))

In [14]:
array_example

array([[[8, 0, 2, 5, 6],
        [6, 7, 0, 0, 5],
        [9, 9, 4, 8, 6],
        [1, 5, 5, 3, 8]],

       [[6, 8, 6, 8, 7],
        [0, 3, 0, 0, 3],
        [4, 6, 7, 9, 1],
        [8, 7, 2, 0, 6]],

       [[9, 9, 9, 2, 0],
        [2, 6, 8, 1, 5],
        [7, 7, 8, 1, 9],
        [3, 5, 8, 8, 3]]])

In [15]:
#From value to the end​
array_example[1:, 1:, 1:]

array([[[3, 0, 0, 3],
        [6, 7, 9, 1],
        [7, 2, 0, 6]],

       [[6, 8, 1, 5],
        [7, 8, 1, 9],
        [5, 8, 8, 3]]])

In [16]:
#From beggining to value​
array_example[:2, :2, :3]

array([[[8, 0, 2],
        [6, 7, 0]],

       [[6, 8, 6],
        [0, 3, 0]]])

In [17]:
#Reversed​
array_example[::-1, ::-1, ::-1]

array([[[3, 8, 8, 5, 3],
        [9, 1, 8, 7, 7],
        [5, 1, 8, 6, 2],
        [0, 2, 9, 9, 9]],

       [[6, 0, 2, 7, 8],
        [1, 9, 7, 6, 4],
        [3, 0, 0, 3, 0],
        [7, 8, 6, 8, 6]],

       [[8, 3, 5, 5, 1],
        [6, 8, 4, 9, 9],
        [5, 0, 0, 7, 6],
        [6, 5, 2, 0, 8]]])

To copy

In [18]:
array_example2 = array_example[1:2:, 2:4:, ::-1].copy()

**Reshape**

In [19]:
values = np.arange(1, 10) #Array of nine values​
grid  = values.reshape((3, 3)) #Using the method of ndarray
print(values)
print(grid)
print(id(values))
print(id(grid))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
138292451279568
138292451279664


Note that the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array

**CONCATENATION AND SPLITTING​**

Concatenation, or joining of two arrays in NumPy, is primarily accomplished through the routines np.concatenate, np.vstack, and np.hstack.

In [20]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [22]:
y

array([3, 2, 1])

Working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions

In [23]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
np.vstack([x, grid]) # vertically stack the arrays​


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [24]:
x

array([1, 2, 3])

In [25]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [27]:
y = np.array([[99], [99]])
np.hstack([grid, y]) # horizontally stack the arrays

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [28]:
y

array([[99],
       [99]])

The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. ​
For each of these, we can pass a list of indices giving the split points:

In [29]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [30]:
grid = np.arange(16).reshape((4, 4))
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [31]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


The key to make the computation fast is to use vectorized operations, generally implemented through NumPy’s universal functions (ufuncs).​

In [34]:
np.arange(5) / np.arange(1, 6)


array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(1, 6)


array([1, 2, 3, 4, 5])

In [35]:
x = np.arange(9).reshape((3, 3))
print(2 ** x)

[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


Computations using vectorization through ufuncs are nearly always more efficient than their counterpart implemented through Python loops, especially as the arrays grow in size.

**COMPARISON OPERATORS**

NumPy also implements comparison operators such as < (less than) and > (greater than) as element-wise ufuncs.​

The result of these comparison operators is always an array with a Boolean data type.

In [36]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])


In [37]:
result_equal = arr1 == arr2
print(result_equal)  # Output: [False False  True False False]


[False False  True False False]


In [38]:
result_not_equal = arr1 != arr2
print(result_not_equal)  # Output: [ True  True False  True  True]


[ True  True False  True  True]


In [39]:
result_greater_than = arr1 > arr2
print(result_greater_than)  # Output: [False False False  True  True]


[False False False  True  True]


In [40]:
result_less_than = arr1 < arr2
print(result_less_than)  # Output: [ True  True False False False]


[ True  True False False False]


In [41]:
np.sum(arr1<6)#To count the number of True entries in a Boolean array

5

In [42]:
np.any(arr2>2)

True

In [43]:
np.all(arr1==2)

False

Masking

In [44]:
x=np.random.randint(10, size=(3,4))
x

array([[9, 1, 0, 3],
       [0, 3, 6, 2],
       [7, 0, 8, 8]])

In [45]:
x<5

array([[False,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [46]:
x[x<5]

array([1, 0, 3, 0, 3, 2, 0])

**Arithmetic Operations**

In [47]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

Subtraction

In [50]:
g = a - b
#np.subtract(a,b) #Subtraction
g

array([-2,  0,  2])

Addition

In [51]:
b + a
#np.add(b,a)

array([4, 4, 4])

Division and Multiplication

In [52]:
# Division
a / b
np.divide(a,b)

array([0.33333333, 1.        , 3.        ])

In [ ]:
#Multiplication
a * b
np.multiply(a,b)

Basic operations

In [ ]:
np.exp(b) #Exponentiation
np.sqrt(b) #Square root
np.sin(a) #Print sines of an array
np.cos(b) #Element-wise cosine
np.log(a) #Element-wise natural logarithm
e.dot(f) #Dot product